#!/bin/bash
# Builds taskdeck.app into the repository root.
set -euo pipefail

cd "$(dirname "$0")"
REPO="$(cd .. && pwd)"
APP="$REPO/taskdeck.app"

# Bake the repository path into the binary so the app can find src/server.js.
cat > Config.swift <<EOF
// Generated by build.sh — do not edit.
let repoPath = "$REPO"
EOF

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"
cp Info.plist "$APP/Contents/Info.plist"

swiftc -O -parse-as-library main.swift Config.swift \
  -framework Cocoa -framework WebKit \
  -o "$APP/Contents/MacOS/taskdeck"

codesign --force --sign - "$APP" 2>/dev/null || true
echo "Built: $APP"
