#!/bin/bash
# Builds taskdeck.app.
#
#   ./macos/build.sh                      # 開発用: リポジトリ直下に taskdeck.app (リポジトリの src/ を参照)
#   ./macos/build.sh --out X.app --repo none --arch universal
#                                         # 配布用: 自己完結バンドルの器 (scripts/package.mjs が呼ぶ)
#
# --repo <path|none>  バイナリに焼き込むリポジトリパス。none なら空文字になり、
#                     アプリは Contents/Resources/app (同梱コピー) だけを使う。
# --arch <arm64|x86_64|universal>  既定はビルドマシンのアーキテクチャ。
set -euo pipefail

cd "$(dirname "$0")"
REPO="$(cd .. && pwd)"
APP="$REPO/taskdeck.app"
REPO_PATH="$REPO"
ARCH="$(uname -m)"

while [ $# -gt 0 ]; do
  case "$1" in
    --out) APP="$2"; shift 2 ;;
    --repo) REPO_PATH="$2"; shift 2 ;;
    --arch) ARCH="$2"; shift 2 ;;
    *) echo "unknown option: $1" >&2; exit 1 ;;
  esac
done
[ "$REPO_PATH" = "none" ] && REPO_PATH=""

# Bake the repository path into the binary so the dev build can find src/server.js.
cat > Config.swift <<EOF
// Generated by build.sh — do not edit.
let repoPath = "$REPO_PATH"
EOF

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp Info.plist "$APP/Contents/Info.plist"

# アプリアイコン (.icns) を生成して同梱
ICONSET="$APP/Contents/Resources/AppIcon.iconset"
swift make_icon.swift "$ICONSET"
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
rm -rf "$ICONSET"

BIN="$APP/Contents/MacOS/taskdeck"
compile() { # <target triple> <output>
  swiftc -O -parse-as-library -target "$1" main.swift Config.swift \
    -framework Cocoa -framework WebKit -o "$2"
}
case "$ARCH" in
  universal)
    compile arm64-apple-macos13.0 "$BIN.arm64"
    compile x86_64-apple-macos13.0 "$BIN.x86_64"
    lipo -create "$BIN.arm64" "$BIN.x86_64" -output "$BIN"
    rm -f "$BIN.arm64" "$BIN.x86_64"
    ;;
  arm64|x86_64) compile "$ARCH-apple-macos13.0" "$BIN" ;;
  *) echo "unknown arch: $ARCH" >&2; exit 1 ;;
esac

codesign --force --sign - "$APP" 2>/dev/null || true
echo "Built: $APP"
