#!/bin/bash
# Builds taskdeck.app into the repository root.
set -euo pipefail

cd "$(dirname "$0")"
REPO="$(cd .. && pwd)"
APP="$REPO/taskdeck.app"

# Bake the repository path into the binary so the app can find src/server.js.
cat > Config.swift <<EOF
// Generated by build.sh — do not edit.
let repoPath = "$REPO"
EOF

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS" "$APP/Contents/Resources"
cp Info.plist "$APP/Contents/Info.plist"

# アプリアイコン (.icns) を生成して同梱
ICONSET="$APP/Contents/Resources/AppIcon.iconset"
swift make_icon.swift "$ICONSET"
iconutil -c icns "$ICONSET" -o "$APP/Contents/Resources/AppIcon.icns"
rm -rf "$ICONSET"

swiftc -O -parse-as-library main.swift Config.swift \
  -framework Cocoa -framework WebKit \
  -o "$APP/Contents/MacOS/taskdeck"

codesign --force --sign - "$APP" 2>/dev/null || true
echo "Built: $APP"
